name: octopus

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: dimitris

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend


#old-----------------------------------------------------
#name: octopus
#services:
#  db:
#    image: postgres
#    ports:
#      - "5432:5432"
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: dimitris
#  ui:
#    image: ghcr.io/devtiro/devtiro-build-task-app:latest
#    ports:
#      - "3000:3000"
#    environment:
#      - BACKEND_HOST=host.docker.internal
#      - BACKEND_PORT=8080
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
##  backend:
##    build: .
##    ports:
##      - "8080:8080"
##    depends_on:
##      - db