package com.dkopsidas.octopus.domain.entity;

public enum AuditAction {
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    USER_LOGOUT,
    USER_REGISTERED,
    USER_REGISTER_FAILED,
    USER_DEACTIVATED,
    USER_UPDATED,
    USER_ROLE_CHANGED,
    INVITE_CODE_GENERATED,
    INVITE_CODE_DELETED,
    TOKEN_REFRESHED,
    COURSE_UPDATED,
    QUESTION_CREATED,
    QUESTION_UPDATED,
    QUESTION_DEACTIVATED,
    QUESTION_IMAGE_UPLOADED,
    QUESTION_IMAGE_DELETED,
    BUNDLE_CREATED,
    CLIENT_AUDIT_EVENT
}
