spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
app.cors.allowed-origins=http://localhost:5173

app.image.upload-dir=/var/www/octopus/images
app.image.base-url=http://localhost:8080/images

spring.web.resources.static-locations=file:${app.image.upload-dir}/
spring.mvc.static-path-pattern=/images/**

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true