spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

app.readonly=true

app.image.upload-dir=/var/www/octopus/images
app.image.base-url=https://octopus.kerberos.network/images

app.cors.allowed-origins=https://octopus.kerberos.network