spring.application.name=octopus
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=dimitris
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
app.cors.allowed-origins=http://localhost:5173

app.image.upload-dir=S:/temp
app.image.base-url=http://localhost:8080/images
spring.web.resources.static-locations=file:${app.image.upload-dir}/
spring.mvc.static-path-pattern=/images/**

#for data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true