spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}

app.image.upload-dir=${APP_IMAGE_UPLOAD_DIR:/var/www/octopus/images}
app.image.base-url=${APP_IMAGE_BASE_URL:http://localhost:8080/images}

spring.web.resources.static-locations=file:${app.image.upload-dir}/
spring.mvc.static-path-pattern=/images/**
app.readonly=${APP_READONLY:false}

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true